Repository CDCgov/prime-simplereport-site, pull requests merged in 2021-03, with the labels that each got.

#84 Use real links in footer link section
  _includes/components/footer--slim.html
Labels: Patient Experience

#83 Update page h1 margins
  _layouts/page.html
  _sass/_uswds-theme-custom-styles.scss
Labels: Patient Experience

#89 Update homepage layout (consistency and refinements)
  _includes/components/footer--slim.html
  _includes/components/hero.html
  _sass/_uswds-theme-custom-styles.scss
  assets/img/animation1.gif
  assets/img/animation2.gif
  pages/home.md
Labels: Growth & Engagement, Patient Experience

#96 Add unsupported browser page to catch attempted IE logins
  _includes/components/hero.html
  _layouts/page.html
  pages/unsupported-browser.html
  yarn.lock
Labels: Growth & Engagement
